{
 "title": "jetson",
 "time": { "from": "2023-06-26T20:20:04.000Z", "to": "2023-06-26T21:20:30.000Z" },
 "panels": [
  {
   "title": "Current ocupancy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(DISTINCT id) AS \"Current IDs\"\r\nFROM\r\n  Customers\r\nWHERE\r\n  `timestamp` = (SELECT MAX(`timestamp`) FROM Customers);\r\n"
    }
   ]
  },
  {
   "title": "Most popular zone",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(CASE WHEN x_pos >= 0 AND x_pos <= 426 THEN 1 END) AS Zona1,\r\n  COUNT(CASE WHEN x_pos >= 427 AND x_pos <= 853 THEN 1 END) AS Zona2,\r\n  COUNT(CASE WHEN x_pos >= 854 AND x_pos <= 1280 THEN 1 END) AS Zona3\r\nFROM Customers \r\nWHERE timestamp = (SELECT MAX(timestamp) FROM Customers);"
    }
   ]
  },
  {
   "title": "Average stay",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(counter) FROM (SELECT COUNT(timestamp) AS counter FROM Customers WHERE $__timeFilter(timestamp) GROUP BY id) AS Counter2\r\n"
    }
   ]
  },
  {
   "title": "Total number of people in store",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CONVERT_TZ(`timestamp`, '+02:00', '+00:00') AS \"time\",\r\n  COUNT(DISTINCT CASE WHEN `x_pos` BETWEEN 0 AND 426 THEN id END) as \"Zone 1\",\r\n  COUNT(DISTINCT CASE WHEN `x_pos` BETWEEN 427 AND 853 THEN id END) as \"Zone 2\",\r\n  COUNT(DISTINCT CASE WHEN `x_pos` BETWEEN 854 AND 1280 THEN id END) as \"Zone 3\"\r\nFROM\r\n  Customers\r\nGROUP BY `timestamp`\r\nORDER BY `timestamp`\r\n"
    }
   ]
  },
  {
   "title": "Duration of stay hostogram",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  duration_seconds,\r\n  COUNT(*) as count\r\nFROM\r\n  (SELECT\r\n     id,\r\n     TIMESTAMPDIFF(second, MIN(CONVERT_TZ(`timestamp`, '+02:00', '+00:00')), MAX(CONVERT_TZ(`timestamp`, '+02:00', '+00:00'))) as duration_seconds\r\n   FROM\r\n     Customers\r\n   WHERE $__timeFilter(timestamp)\r\n   GROUP BY id) as subquery\r\nWHERE duration_seconds between 5 AND 1800\r\nGROUP BY duration_seconds\r\n"
    }
   ]
  }
 ]
}